[package]
name = "enigma"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[lib]
crate-type = ["cdylib"]

[dependencies]
aes-gcm = "0.10.1"
num = "0.4.0"
ring = "0.17.0-alpha.11"